apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2b-public
    crossplane.io/external-create-pending: "2025-11-12T14:08:17Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:08:17Z"
    crossplane.io/external-name: rtbassoc-0005fcd25dce089ac
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-6cd3caaa3e76
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626387"
  uid: 1b16eb91-b4c5-4413-b9c2-5b7bfd95d184
spec:
  forProvider:
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    routeTableIdRef:
      name: configuration-aws-network-8068c56aeb15
      namespace: default
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-0eda68fa3618e7996
    subnetIdRef:
      name: configuration-aws-network-600dcf320477
      namespace: default
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-west-2b
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-0005fcd25dce089ac
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    subnetId: subnet-0eda68fa3618e7996
  conditions:
  - lastTransitionTime: "2025-11-12T14:19:13Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:09:21Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:08:19Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
