apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2a-private
    crossplane.io/external-create-pending: "2025-11-12T14:08:17Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:08:17Z"
    crossplane.io/external-name: rtbassoc-035176ea1fa1397bf
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-f9963f3da42d
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626421"
  uid: 16bfb223-dbc1-4241-9f01-a0e2f485be0b
spec:
  forProvider:
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    routeTableIdRef:
      name: configuration-aws-network-8068c56aeb15
      namespace: default
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-06b0d926a2762f440
    subnetIdRef:
      name: configuration-aws-network-bb70cf9abdd4
      namespace: default
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: private
        zone: us-west-2a
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-035176ea1fa1397bf
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    subnetId: subnet-06b0d926a2762f440
  conditions:
  - lastTransitionTime: "2025-11-12T14:19:22Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:09:21Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:08:18Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
