apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  annotations:
    crossplane.io/composition-resource-name: route
    crossplane.io/external-create-pending: "2025-11-12T14:08:18Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:08:18Z"
    crossplane.io/external-name: r-rtb-06b2e56bbb21409c51080289494
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-6c7ee6400477
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626452"
  uid: 6317ce7c-47c1-4ccb-bc55-aaad98477f44
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayId: igw-052aaded484c10ee8
    gatewayIdRef:
      name: configuration-aws-network-c44b88ac52be
      namespace: default
    gatewayIdSelector:
      matchControllerRef: true
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    routeTableIdRef:
      name: configuration-aws-network-8068c56aeb15
      namespace: default
    routeTableIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    carrierGatewayId: ""
    coreNetworkArn: ""
    destinationCidrBlock: 0.0.0.0/0
    destinationIpv6CidrBlock: ""
    destinationPrefixListId: ""
    egressOnlyGatewayId: ""
    gatewayId: igw-052aaded484c10ee8
    id: r-rtb-06b2e56bbb21409c51080289494
    instanceId: ""
    instanceOwnerId: ""
    localGatewayId: ""
    natGatewayId: ""
    networkInterfaceId: ""
    origin: CreateRoute
    region: us-west-2
    routeTableId: rtb-06b2e56bbb21409c5
    state: active
    transitGatewayId: ""
    vpcEndpointId: ""
    vpcPeeringConnectionId: ""
  conditions:
  - lastTransitionTime: "2025-11-12T14:19:31Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:09:22Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:08:19Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
