apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/composition-resource-name: sg
    crossplane.io/external-create-pending: "2025-11-12T14:07:43Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:07:43Z"
    crossplane.io/external-name: sg-01f80f38de3da15fe
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-8d638d44a408
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626242"
  uid: 92dfd6de-e458-49c1-8a7e-ea7637ffe1fe
spec:
  forProvider:
    description: Allow access to databases
    name: platform-ref-aws-cluster
    region: us-west-2
    tags:
      crossplane-kind: securitygroup.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-8d638d44a408
      crossplane-providerconfig: default
      fromValue: tagFromValue
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    vpcId: vpc-0e7338c7029100471
    vpcIdRef:
      name: configuration-aws-network-1b95946a5b6b
      namespace: default
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:security-group/sg-01f80f38de3da15fe
    description: Allow access to databases
    id: sg-01f80f38de3da15fe
    ingress:
    - cidrBlocks:
      - 0.0.0.0/0
      description: Everywhere
      fromPort: 3306
      protocol: tcp
      self: false
      toPort: 3306
    - cidrBlocks:
      - 0.0.0.0/0
      description: Everywhere
      fromPort: 5432
      protocol: tcp
      self: false
      toPort: 5432
    name: platform-ref-aws-cluster
    ownerId: "609897127049"
    region: us-west-2
    revokeRulesOnDelete: false
    tags:
      crossplane-kind: securitygroup.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-8d638d44a408
      crossplane-providerconfig: default
      fromValue: tagFromValue
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    tagsAll:
      crossplane-kind: securitygroup.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-8d638d44a408
      crossplane-providerconfig: default
      fromValue: tagFromValue
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    vpcId: vpc-0e7338c7029100471
  conditions:
  - lastTransitionTime: "2025-11-12T14:18:29Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:08:18Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:07:48Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
