apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/composition-resource-name: sgrp
    crossplane.io/external-create-pending: "2025-11-12T14:08:17Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:08:17Z"
    crossplane.io/external-name: sgrule-4128324983
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-1a6c7216b2d8
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626138"
  uid: 7930840b-a3ee-4a14-9eb7-25de60ba3641
spec:
  forProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 5432
    protocol: tcp
    region: us-west-2
    securityGroupId: sg-01f80f38de3da15fe
    securityGroupIdRef:
      name: configuration-aws-network-8d638d44a408
      namespace: default
    securityGroupIdSelector:
      matchControllerRef: true
    toPort: 5432
    type: ingress
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 5432
    id: sgrule-4128324983
    protocol: tcp
    region: us-west-2
    securityGroupId: sg-01f80f38de3da15fe
    securityGroupRuleId: sgr-0d8c3409efaf41dc8
    self: false
    toPort: 5432
    type: ingress
  conditions:
  - lastTransitionTime: "2025-11-12T14:17:59Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:08:25Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:08:20Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
