apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: subnet-us-west-2a-public
    crossplane.io/external-create-pending: "2025-11-12T14:07:43Z"
    crossplane.io/external-create-succeeded: "2025-11-12T14:07:43Z"
    crossplane.io/external-name: subnet-07943c337b25f3e5a
  creationTimestamp: "2025-11-12T14:07:14Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 4
  labels:
    access: public
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
    zone: us-west-2a
  name: configuration-aws-network-5264b4e8cc04
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: 283a30f0-fd42-4766-97a8-ac28d501d056
  resourceVersion: "626159"
  uid: 564fb3f0-db15-4e37-ad87-c3bd06d9a045
spec:
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 192.168.0.0/18
    mapPublicIpOnLaunch: true
    privateDnsHostnameTypeOnLaunch: ip-name
    region: us-west-2
    tags:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5264b4e8cc04
      crossplane-providerconfig: default
      fromValue: tagFromValue
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    vpcId: vpc-0e7338c7029100471
    vpcIdRef:
      name: configuration-aws-network-1b95946a5b6b
      namespace: default
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:subnet/subnet-07943c337b25f3e5a
    assignIpv6AddressOnCreation: false
    availabilityZone: us-west-2a
    availabilityZoneId: usw2-az1
    cidrBlock: 192.168.0.0/18
    customerOwnedIpv4Pool: ""
    enableDns64: false
    enableLniAtDeviceIndex: 0
    enableResourceNameDnsARecordOnLaunch: false
    enableResourceNameDnsAaaaRecordOnLaunch: false
    id: subnet-07943c337b25f3e5a
    ipv6CidrBlock: ""
    ipv6CidrBlockAssociationId: ""
    ipv6Native: false
    mapCustomerOwnedIpOnLaunch: false
    mapPublicIpOnLaunch: true
    outpostArn: ""
    ownerId: "609897127049"
    privateDnsHostnameTypeOnLaunch: ip-name
    region: us-west-2
    tags:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5264b4e8cc04
      crossplane-providerconfig: default
      fromValue: tagFromValue
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    tagsAll:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5264b4e8cc04
      crossplane-providerconfig: default
      fromValue: tagFromValue
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
      replaceFromXR: value1
      replaceFromXR2: value2
      retainFromXR: optional1
      retainFromXR2: optional2
    vpcId: vpc-0e7338c7029100471
  conditions:
  - lastTransitionTime: "2025-11-12T14:18:06Z"
    observedGeneration: 4
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-11-12T14:08:00Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-11-12T14:07:55Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
