apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: production-environment
  labels:
    environment: production
data:
  additionalTags:
    replaceFromXR: value1
    replaceFromXR2: value2
  optionalTags:
    retainFromXR: optional1
    retainFromXR2: optional2
  ignoreTagKeysReplace:
    - ignoreReplace1
    - ignoreReplace2
    # if there is a conflict, keep the existing tags
  ignoreTagKeysRetain:
    - ignoreRetain1
